name: Manual Test

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: The ref or commit SHA to checkout
        required: false
      notify:
        type: boolean
        description: Should notify Slack?
        required: false
      color:
        type: string
      echo:
        type: boolean
        description: Should echo the ref?
        required: false

jobs:
  #alsdkjf asdf
  # Resolve-Ref-Sha:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     sha: ${{ steps.resolve.outputs.sha }}
  #   steps:
  #     - name: Resolve Ref
  #       id: resolve
  #       run: echo "$(git rev-parse ${{ inputs.ref }})" >> "$GITHUB_OUTPUT"
  Echo:
    if: ${{ inputs.echo == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "github.sha ${{ github.sha }}"
          echo "github.workflow_sha ${{ github.workflow_sha }}"
  Checkout:
    needs: Echo
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          ref: ${{ inputs.ref || github.sha }}
  Notify:
    needs: Echo
    if: ${{ always() && inputs.notify == true && (needs.Echo.result == 'success' || needs.Echo.result == 'skipped') }}
    uses: ./.github/workflows/slack-notify.yaml
    with:
      channel: feed-slack-webhook-test
      message: ${{ needs.Echo.result }}
      color: ${{ inputs.color }}
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}