name: Manual Test

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: The ref or commit SHA to checkout
        required: false
      notify:
        type: boolean
        description: Should notify Slack?
        required: false
      color:
        type: string

jobs:
  #alsdkjf
  # Resolve-Ref-Sha:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     sha: ${{ steps.resolve.outputs.sha }}
  #   steps:
  #     - name: Resolve Ref
  #       id: resolve
  #       run: echo "$(git rev-parse ${{ inputs.ref }})" >> "$GITHUB_OUTPUT"
  Checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          ref: ${{ inputs.ref || github.sha }}
  Notify:
    needs: Checkout
    if: ${{ inputs.notify == true }}
    uses: ./.github/workflows/slack-notify.yaml
    with:
      channel: feed-slack-webhook-test
      message: ${{ inputs.ref || github.sha }}
      color: ${{ inputs.color }}
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}