name: Manual Tag

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The commit SHA to tag'
        required: true
        default: ''
      tag_name:
        description: 'The tag name to create'
        required: true
        default: ''

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Force push tag
      run: |
        git tag -f ${{ github.event.inputs.tag_name }} ${{ github.event.inputs.commit_sha }}
        git push origin ${{ github.event.inputs.tag_name }} --force
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}