name: Manual Tag

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The commit SHA to tag'
        required: true
        default: ''
      tag_name:
        description: 'The tag name to create'
        required: true
        default: ''

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.commit_sha }}

    - name: Force push tag
      run: |
        git tag ${{ inputs.tag_name }} -f
        git push origin ${{ inputs.tag_name }} -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}