name: Manual Tag

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
      name:
        type: string
        required: true

jobs:
  Checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          ref: ${{ github.sha }}
  Tag:
    needs: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        run: |
          echo "github actor 1 ${{ github.actor }}"
          echo "github actor 2 ${GITHUB_ACTOR}"
          git tag ${{ inputs.name }} -f ${{ inputs.ref }}
          git push origin ${{ inputs.name }} -f
