name: Slack Notify

on:
  workflow_call:
    inputs:
      channel:
        type: string
        description: The Slack to post the message to
        required: true
      message:
        type: string
        description: The message to post to Slack
        required: true
    secrets:
      slack_webhook_url:
        description: The SLACK_WEBHOOK_URL secret
        required: true

jobs:
  Slack-Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "${{ inputs.channel }}",
              "attachments": [
                {
                  "text": "${{ inputs.message }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
