name: Test Slack

on:
  workflow_dispatch:
    inputs:
      channel:
        type: string
        required: true
      message:
        type: string
        required: true
      color:
        type: string

jobs:
  Test:
    uses: ./.github/workflows/slack-notify.yaml
    with:
      channel: ${{ inputs.channel }}
      message: ${{ inputs.message }}
      color: ${{ inputs.color }}
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
